version: '3.8'

services:
  backend:
    build:
      context: ./  # Build context remains the root of the project (where docker-compose.yml is)
      dockerfile: backend/Dockerfile  # Use the Dockerfile in the backend folder
    env_file:
      - .env  # Load environment variables into the backend container
    ports:
      - "8080:8080"  # Map backend container port 8080 to localhost:8080
    environment:
      NODE_ENV: development

  frontend:
    build:
      context: ./  # Build context remains the root of the project
      dockerfile: frontend/Dockerfile  # Use the Dockerfile in the frontend folder
    env_file:
      - .env  # Load environment variables into the frontend container
    ports:
      - "3000:3000"  # Map frontend container port 3000 to localhost:3000
    environment:
      NODE_ENV: development
    depends_on:
      - backend  # Ensure the backend service starts before the frontend
