# docker-compose.yml

version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env  # Since .env is in the root directory
    ports:
      - "3001:3001"
    depends_on:
      - frontend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - .env  # Since .env is in the root directory
    ports:
      - "3000:3000"
