version: '3.8'

services:
  backend:
    build:
      context: ./  # Build context remains the root of the project
      dockerfile: backend/Dockerfile  # Use the Dockerfile in the backend folder
    env_file:
      - .env
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: development

  frontend:
    build:
      context: ./  # Build context remains the root of the project
      dockerfile: frontend/Dockerfile
    env_file:
      - .env
    ports:
      - "3000:8080"
    environment:
      NODE_ENV: production
    depends_on:
      - backend
