name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Check out the code
        uses: actions/checkout@v2

      # Step 2: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      # Step 3: Log in to Amazon ECR
      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      # Step 4: Create ECR Repositories if they don't exist
      - name: Create ECR Repository for Backend (if not exists)
        run: |
          aws ecr describe-repositories --repository-names backend || \
          aws ecr create-repository --repository-name backend
        env:
          AWS_REGION: us-west-2

      - name: Create ECR Repository for Frontend (if not exists)
        run: |
          aws ecr describe-repositories --repository-names frontend || \
          aws ecr create-repository --repository-name frontend
        env:
          AWS_REGION: us-west-2

      # Step 5: Build and push backend image to ECR
      - name: Build and push backend image to ECR
        run: |
          docker build -t backend ./backend
          docker tag backend:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-west-2.amazonaws.com/backend:latest
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-west-2.amazonaws.com/backend:latest

      # Step 6: Build and push frontend image to ECR
      - name: Build and push frontend image to ECR
        run: |
          docker build -t frontend ./frontend
          docker tag frontend:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-west-2.amazonaws.com/frontend:latest
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-west-2.amazonaws.com/frontend:latest

      # Step 7: Package and Upload Deployment Artifact
      - name: Create deployment package
        run: zip Dockerrun.zip Dockerrun.aws.json

      # Step 8: Deploy to Elastic Beanstalk
      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: cs130-test
          environment_name: cs130-test-env
          version_label: github-${{ github.sha }}
          region: us-west-2
          deployment_package: Dockerrun.zip
